using Content.Client.UserInterface.Controls;
using Content.Shared.Misfits.Administration.DoorLogs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Misfits.Administration.UI.DoorLogs;

[GenerateTypedNameReferences]
public sealed partial class DoorLogsWindow : FancyWindow
{
    public DoorLogsWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(List<DoorLogEntry> entries)
    {
        LogList.RemoveAllChildren();

        if (entries.Count == 0)
        {
            LogList.AddChild(new Label
            {
                Text = Loc.GetString("misfits-door-logs-empty"),
                Margin = new Thickness(0, 8, 0, 0),
                FontColorOverride = Color.Gray,
            });
            return;
        }

        foreach (var entry in entries)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 12,
                Margin = new Thickness(0, 2),
            };
            row.AddChild(new Label { Text = entry.Time.ToString(@"hh\:mm\:ss"), MinWidth = 160, ClipText = true });
            row.AddChild(new Label { Text = entry.DoorPrototype, MinWidth = 420, ClipText = true });
            row.AddChild(new Label { Text = entry.DestroyedBy, MinWidth = 200, ClipText = true });
            LogList.AddChild(row);
        }
    }
}
